### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ohitstom** [BlackusPL/OnesPluginLibrary#3]
i got force updated to 2.0.0 of zerepluginlib and now it wont let me use this patch, and when it does it either doesnt work or automatically resets

**Comment by Misha-133** [comment]
> i got force updated to 2.0.0 of zerepluginlib and now it wont let me use this patch, and when it does it either doesnt work or automatically resets

As a temporary solution you can change plugin version in code to something greater than 2

for example change this from
`version: "1.2.35",`
to `version: "2.2.35",`

this will work, but it's genuinely not the best way to solve this issue
